//export * from './alertLabel';
export * from './buttons';
export * from './titles';
//export * from './input';
//export * from './label';
export * from './link';
export * from './picture';
//export * from './select';
//export * from './checkboxOrRadio';
